SELECT E.ID
FROM ECOLI_DATA E
LEFT OUTER JOIN ECOLI_DATA PE ON E.PARENT_ID = PE.ID
LEFT OUTER JOIN ECOLI_DATA PPE ON PE.PARENT_ID = PPE.ID
WHERE PPE.PARENT_ID IS NULL AND PE.PARENT_ID IS NOT NULL
ORDER BY E.ID
