SELECT PE.ID, COALESCE(CE.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA PE
LEFT OUTER JOIN (
    SELECT E.PARENT_ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA E
    GROUP BY E.PARENT_ID
) CE ON PE.ID = CE.PARENT_ID
ORDER BY PE.ID