SELECT S.ROUTE, 
    CONCAT(ROUND(SUM(S.D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(S.D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE S
GROUP BY S.ROUTE
ORDER BY SUM(S.D_BETWEEN_DIST) DESC