SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    MAX(E.SIZE_OF_COLONY) OVER (PARTITION BY YEAR(E.DIFFERENTIATION_DATE))
    - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
ORDER BY YEAR, YEAR_DEV